CREATE DATABASE TESTE1;

use TESTE1;
cReaTe tAbLe tbADM(

CodigoADM Varchar(40) not null,
SenhaADM Varchar(40) not null
);

drop table tbADM;
insert into tbADM (CodigoADM, SenhaADM)
Values ("151", "Etec2023ADM");



create table tbcomentarios(

nomeVeterano varchar(90),
rmVeterano varchar(5),
texto text(2000) not null,
estrelas tinyint not null,
curso VARCHAR(4) NOT NULL,

CONSTRAINT curso_check CHECK (curso IN ('INFO', 'ADM', 'RH', 'JUR', 'MKT')),
CONSTRAINT estrelas_check CHECK (estrelas BETWEEN 1 AND 5)
);
drop table tbcomentarios;

insert into tbcomentarios(nomeVeterano, curso, texto, estrelas)
values ("Renan", "INFO", "muito bom", "5");

select * from tbcomentarios;

select * from tbADM;

create table tbINFO(
	nome varchar(255),
    rm int(10) primary key
);
drop table tbINFO;

insert into tbINFO (nome, rm)
values (
"ADRYELLY DE OLIVEIRA", "31767"
"ANA CLARA MAXIMINO","31957"
"ARTHUT BARBEIRO AGUIAR", "31782"
"BRUNO MENDES DA SILVA", "31777"
"BRYAN BELARMINO MOREIRA", "31766"
"CARLOS ALEXANDRE DA SILVA GOMES","31765"
"CAUÃ ALTRON PULIANI", "31790"
"CAUÊ RODRIGUES NUNES EVANGELISTA", "31958"
"CÉSAR AUGUSTO FREITAS SAVOLDI", "31789"
"ESTEVÃO DA SILVA LUCRECIO", "31888"
"FELIPE NETTO DA COSTA", "31275"
"FELIPE SILVA DE SOUZA", "31786"
"GABRIEL CESAR RODRIGUES", "31783"
"GABRIEL PARIJANI CUSTODIO", "31788"
"GABRIEL PINHEIRO CHAGAS FERNANDES", "31774"
"HENRIQUE RODRIGUES BARBOSA", "31769"
"INGRID CAVALLI DA SILVA", "31781"
"ISABELA DE OLIVERA GUESSI", "31762"
"JHONATAN GOBETI NUNES", "31768"
"JOÃO GILBERTO CANAL FAVARO", "31883"
"JOÃO PEDRO DE LIMA SANTOS", "31885"
"JOÃO PEDRO DE OLIVEIRA SPERA", "31772"
"JOÃO PEDRO PAULINO SPINDA", "31884"
"JULIA BELLINI SORRENTE", "31784"
"KAIQUE ALVES DE CONTI", "31776"
"LETÍCIA DA SILVA FRANCISCO", "31780"
"LETÍCIA PEREIRA DA SILVA", "31770"
"LETYCIA CONDE DA CRUZ", "31979"
"LUCAS ALESSANDRO MENDONÇA BENTO", "31889"
"LUCAS DANIEL TAVARES MAXIMO", "31773"
"LUIGI AUGUSTO VAZ CASSIANO DA SILVA", "31787"
"MARCOS ALEXANDRE ALVES ARAUJO", "31778"
"PABLO HENRIQUE NOGUEIRA", "31887"
"PEDRO HENRIQUE ALVES DIAS", "31886"
"PEDRO HENRIQUE DEZEM", "31763"
"RAFAEL DO NASCIMENTO", "31761"
"RENAN BRITO DE MORAES", "31775"
"RIAD ABBES BERNARDE", "31764"
"VINICIUS SILVA GUEDES", "31001"
);

